services:
  - type: web
    name: api-rue-lucas
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGO_URI
        fromDatabase:
          name: rue-lucas-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "*"

databases:
  - name: rue-lucas-db
    plan: free
